name: null

channels:
  - conda-forge
  - defaults
  - pyviz

dependencies:
  - jupyterlab
  - matplotlib
  - numpy=1.17
  - pandas
  - pyarrow
  - python
  - xlrd
  - plotly
  - ipywidgets
  - nodejs
  - psutil
  - requests
  - bokeh
  - pyviz::panel
  - hvplot
  - jupyter-panel-proxy