name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - jupyterlab=1.2
  - matplotlib=3.1
  - pandas=0.25
  - pyarrow=0.14
  - python=3.6
  - scikit-learn=0.21
  - xlrd=1.2
  - fbprophet
  - statsmodels
  - plotly=4.4
  - ipywidgets=7.5
  - nodejs
  - psutil
  - requests
  - seaborn